name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
        toxenv: [quality, docs, 'py312']
    env:
      RUNJSHINT: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          architecture: x64
      - run: pip install -r requirements/ci.txt
      - name: Run tox
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox
      - name: Run Coverage
        if: matrix.toxenv == 'py312'
        uses: codecov/codecov-action@v3
        with:
          flags: unittests
          fail_ci_if_error: false
